coverage:
  precision: 3
  round: nearest
  require_ci_to_pass: no
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    patch:
      default:
        target: auto
        threshold: 0.25%
